jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600

adapters:
  r2dbc:
    host: ${DB_HOST}
    port: 5432
    database: arka
    schema: micro_stock
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}
    user: ${adapters.r2dbc.username}
    password: ${adapters.r2dbc.password}
    schemas: ${adapters.r2dbc.schema}
    baseline-on-migrate: true
    locations: classpath:db/migration


  r2dbc:
    url: r2dbc:postgresql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}?schema=${adapters.r2dbc.schema}
    username: ${adapters.r2dbc.username}
    password: ${adapters.r2dbc.password}

logging:
  level:
    org.flywaydb: DEBUG

server:
  port: 8070

webclient:
  user:
    base-url: http://localhost:8080/api/users

resilience4j:
  circuitbreaker:
    instances:
      userService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 500ms
  bulkhead:
    instances:
      userService:
        max-concurrent-calls: 10
        max-wait-duration: 10ms
  timelimiter:
    instances:
      userService:
        timeout-duration: 2s
        cancel-running-future: true